---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-play
  region: us-east-1
  version: '1.12'

nodeGroups:
  - name: workers
    minSize: 1
    maxSize: 1
    ssh:
      publicKeyPath: id_rsa.pub
    instancesDistribution:
      instanceTypes: ["m5.8xlarge", "m5.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
