---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-play-2
  region: us-east-1
  version: '1.14'

nodeGroups:
  - name: workers-v2
    minSize: 2
    maxSize: 2
    instancesDistribution:
      instanceTypes: ["m5.8xlarge", "m5.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0