apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  labels:
    app: go-server
spec:
  replicas: 700
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: 098086232615.dkr.ecr.us-east-1.amazonaws.com/go-server:latest
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelay: 3
        periodSeconds: 10