name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build image
        run: docker build --tag go-server .
      - name: Login to ECR
        id: ecr-login
        uses: jwalton/gh-ecr-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
      - name: Push to ECR
        run: |
          docker tag go-server:latest ${{ steps.ecr-login.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/go-server:latest
          docker push ${{ steps.ecr-login.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/go-server:latest
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@a7cda45617e36f767b67b6c69cbfa045641c8620
        with:
          args: 'eks-play image build finished'
